# The environment of the application, one of production, development, staging, testing or local
env: local

# The gRPC address
grpc:
  addr: :9090

# The name of the application
name: app

# The version of the application
version: 0.1.0

# The http address
http:
  addr: :8080

# The global logging level and format
log:
  format: logfmt
  level: debug

# The database configuration
gorm:
  default:
    allowGlobalUpdate: false
    createBatchSize: 0
    database: mysql
    disableAutomaticPing: false
    disableForeignKeyConstraintWhenMigrating: false
    disableNestedTransaction: false
    dryRun: false
    dsn: root@tcp(127.0.0.1:3306)/app?charset=utf8mb4&parseTime=True&loc=Local
    fullSaveAssociations: false
    namingStrategy:
      singularTable: false
      tablePrefix: ""
    prepareStmt: false
    queryFields: false
    skipDefaultTransaction: false
  foo:
    allowGlobalUpdate: false
    createBatchSize: 0
    database: mysql
    disableAutomaticPing: false
    disableForeignKeyConstraintWhenMigrating: false
    disableNestedTransaction: false
    dryRun: false
    dsn: root@tcp(127.0.0.1:3306)/foo?charset=utf8mb4&parseTime=True&loc=Local
    fullSaveAssociations: false
    namingStrategy:
      singularTable: false
      tablePrefix: ""
    prepareStmt: false
    queryFields: false
    skipDefaultTransaction: false
  bar:
    allowGlobalUpdate: false
    createBatchSize: 0
    database: mysql
    disableAutomaticPing: false
    disableForeignKeyConstraintWhenMigrating: false
    disableNestedTransaction: false
    dryRun: false
    dsn: root@tcp(127.0.0.1:3306)/bar?charset=utf8mb4&parseTime=True&loc=Local
    fullSaveAssociations: false
    namingStrategy:
      singularTable: false
      tablePrefix: ""
    prepareStmt: false
    queryFields: false
    skipDefaultTransaction: false

